postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: adminpass
  ports:
    - '5432:5432'
  volumes:
    - ~/.docker-volumes/boilerplate/postgresql/data:/var/lib/postgresql/data

boilerplate:
  build: .
  command: gunicorn -b 0.0.0.0:8000 --reload --access-logfile -  --env DJANGO_SETTINGS_MODULE=boilerplate.settings "boilerplate.wsgi"
  environment:
    PYTHONUNBUFFERED: true
  links:
    - postgres
  volumes:
    - .:/boilerplate
  ports:
    - '8000:8000'
